# Generated by Django 3.2.3 on 2021-05-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_create_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create',
            options={'verbose_name': 'blog', 'verbose_name_plural': 'blog'},
        ),
    ]
