# Generated by Django 3.2.3 on 2021-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custmer_name', models.CharField(max_length=50)),
                ('custmer_email', models.CharField(max_length=50)),
                ('custmer_phonenumber', models.CharField(max_length=20)),
                ('custmer_content', models.TextField()),
            ],
        ),
    ]
