# Generated by Django 3.2.3 on 2021-05-30 08:20

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='blog/'),
        ),
    ]
