# Generated by Django 3.2.3 on 2021-05-30 15:22

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=200)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MyArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myart_name', models.CharField(max_length=200)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=200)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WebDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=200)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='')),
            ],
        ),
    ]
