# Generated by Django 3.2.3 on 2021-05-30 15:27

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_logoart_myart_videoart_webdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoart',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='logoart'),
        ),
        migrations.AlterField(
            model_name='myart',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='myart'),
        ),
        migrations.AlterField(
            model_name='videoart',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='videoart'),
        ),
        migrations.AlterField(
            model_name='webdesign',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='design'),
        ),
    ]
