# Generated by Django 3.2.3 on 2021-06-05 07:10

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210531_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoart',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='logoarts/'),
        ),
        migrations.AlterField(
            model_name='myart',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='myarts/'),
        ),
        migrations.AlterField(
            model_name='videoart',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='videoarts/'),
        ),
        migrations.AlterField(
            model_name='webdesign',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='designs/'),
        ),
    ]
